#================
#=== Automations
#================
automation:

  #===================================================
  #=== Notify about irrigation events when on holiday
  #===================================================
  - alias: Irrigation - Notify about irrigation events when on holiday
    initial_state: on
    trigger:
      - platform: state
        entity_id:
        - input_boolean.cycle1_running
        - input_boolean.cycle2_running

    condition:
      - condition: state
        entity_id: binary_sensor.holiday_mode
        state: 'on'
    
    action:
      - service_template: >
          {% if trigger.to_state.state == 'on' %}
            script.notify_irrigation_start
          {% else %}
            script.notify_irrigation_end
          {% endif %}
        data_template:
          cycle: >
            {% if trigger.entity_id == 'input_boolean.cycle1_running' %}
              1
            {% else %}
              2
            {% endif %}
        
          
#============
#=== Scripts
#============
script:

  #===============================
  #=== Notify when a cycle starts
  #===   Called with
  #===    {{ cycle }} 
  #===============================
  notify_irrigation_start:    
    sequence:
      - service: script.notify
        data_template:
          tell: steve_and_sarah
          message: >
            {% set cycle_map = {
              '1': 'morning',
              '2': 'afternoon'
            } %}
            {% set cycle_time = cycle_map[cycle] %}

            {% if is_state('input_boolean.cycle' + cycle + '_use_weather_adjustment', 'off') %}
              {% set total_time = states('input_number.cycle' + cycle + '_zone1_duration') | int
                                + states('input_number.cycle' + cycle + '_zone2_duration') | int
                                + states('input_number.cycle' + cycle + '_zone3_duration') | int
                                + states('input_number.cycle' + cycle + '_zone4_duration') | int
                                + states('input_number.cycle' + cycle + '_zone5_duration') | int %}

            {% else %}
              {% set total_time = states('input_number.adjusted_cycle' + cycle + '_zone1_duration') | int
                                + states('input_number.adjusted_cycle' + cycle + '_zone2_duration') | int
                                + states('input_number.adjusted_cycle' + cycle + '_zone3_duration') | int
                                + states('input_number.adjusted_cycle' + cycle + '_zone4_duration') | int
                                + states('input_number.adjusted_cycle' + cycle + '_zone5_duration') | int %}
            {% endif %}

            I thought you'd like to know that the {{cycle_time}} irrigation cycle has just started.


            I expect it will take about {{ total_time }} minutes to finish but I'll let you know when it has.


            Don't worry your garden is safe with me. I hope you're having a lovely holiday!


  #=============================
  #=== Notify when a cycle ends
  #===   Called with
  #===    {{ cycle }} 
  #=============================
  notify_irrigation_end:    
    sequence:
      - service: script.notify
        data_template:
          tell: steve_and_sarah
          message: >
            {% set cycle_map = {
              '1': 'morning',
              '2': 'afternoon'
            } %}
            {% set cycle_time = cycle_map[cycle] %}

            All the {{cycle_time}} watering is done.
